import "./globals.css";
import Footer from "./ui/footer/Footer";
import Contact from "./ui/contact/Contact";
import Nav from "./ui/navbar/Nav";

// const inter = Inter({ subsets: ["persian"] });

export const metadata = {
  title: "کارگزاری فارابی",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <div className="min-h-full">
        <div className="">
          <Contact />
          <Nav />
          {children}
          <Footer />
        </div>
      </div>
    </html>
  );
}
